services:
  alloy:
    image: grafana/alloy:v1.18.1
    container_name: alloy
    restart: unless-stopped
    depends_on:
      - socket-proxy
    volumes:
      - ./config/config.alloy:/etc/alloy/config.alloy:ro
      - ./data:/var/lib/alloy/data
    networks:
      - monitoring
      - socket-proxy

  socket-proxy:
    image: wollomatic/socket-proxy:1.12.3
    container_name: alloy-socket-proxy
    restart: unless-stopped
    user: "65534:983"
    mem_limit: 64M
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    command:
      - '-loglevel=info'
      - '-listenip=0.0.0.0'
      - '-allowfrom=alloy'
      - '-allowGET=/v1\..{1,2}/(version|containers/.*|events.*|networks.*)'
      - '-allowGET=/_ping'
      - '-allowHEAD=/_ping'
      - '-watchdoginterval=3600'
      - '-stoponwatchdog'
      - '-shutdowngracetime=5'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - socket-proxy

networks:
  monitoring:
    external: true
  socket-proxy:
    internal: true
