services:
  authelia:
    image: authelia/authelia:4.39.22
    container_name: authelia
    restart: unless-stopped
    security_opt:
      - no-new-privileges
    user: "1000:1000"
    command:
      - "authelia"
      - "--config"
      - "/config/configuration.yml"

    environment:
      - X_AUTHELIA_CONFIG_FILTERS=template
      - DOMAIN=${DOMAIN:?}
      - AUTHELIA_SESSION_SECRET_FILE=/secrets/session_secret
      - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/secrets/storage_encryption_key
      - AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE=/secrets/jwt_secret

    labels:
      - traefik.enable=true
      - traefik.http.routers.authelia.rule=Host(`auth.${DOMAIN:?}`)
      - traefik.http.routers.authelia.entrypoints=websecure
      - traefik.http.routers.authelia.tls=true
      - traefik.http.routers.authelia.tls.certresolver=letsencrypt
      - traefik.http.routers.authelia.middlewares=rate-limit@file,frame-deny@file
      - traefik.http.services.authelia.loadbalancer.server.port=9091
      - traefik.docker.network=auth

    volumes:
      - ./config:/config:ro
      - ./data:/data
      - ./secrets:/secrets:ro

    networks:
      - auth

networks:
  auth:
    external: true
