services:
  traefik:
    image: traefik:v3.7.13
    container_name: traefik
    restart: unless-stopped
    user: "995:981"
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    environment:
      - TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_EMAIL=${ACME_EMAIL}

    secrets:
      - dashboard_auth_users
      - monitoring_auth_users

    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.rule=Host(`traefik.${DOMAIN}`)
      - traefik.http.routers.dashboard.entrypoints=websecure
      - traefik.http.routers.dashboard.tls=true
      - traefik.http.routers.dashboard.tls.certresolver=letsencrypt
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.routers.dashboard.middlewares=admin@file,dashboard-auth@file

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./traefik.yml:/traefik.yml:ro
      - ./dynamic:/dynamic:ro
      - ./letsencrypt:/letsencrypt

    depends_on:
      - socket-proxy

    networks:
      - proxy
      - auth
      - socket-proxy


  socket-proxy:
    image: wollomatic/socket-proxy:1.12.3
    container_name: traefik-socket-proxy
    restart: unless-stopped
    user: "65534:983"
    mem_limit: 64M
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    command:
      - '-loglevel=info'
      - '-listenip=0.0.0.0'
      - '-allowfrom=traefik'
      - '-allowGET=/v1\..{1,2}/(version|containers/.*|events.*)'
      - '-allowHEAD=/_ping'
      - '-watchdoginterval=3600'
      - '-stoponwatchdog'
      - '-shutdowngracetime=5'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - socket-proxy

secrets:
  dashboard_auth_users:
    file: ./secrets/dashboard_auth_users
  monitoring_auth_users:
    file: ./secrets/monitoring_auth_users

networks:
  proxy:
    external: true
  auth:
    external: true
  socket-proxy:
    internal: true
