groups:
  - name: node-filesystem
    rules:
      - alert: NodeFilesystemSpaceFillingUp
        expr: |
          (
            node_filesystem_avail_bytes{job="node_exporter"} / node_filesystem_size_bytes{job="node_exporter"} * 100 < 40
          and
            predict_linear(node_filesystem_avail_bytes{job="node_exporter"}[6h], 24*60*60) < 0
          and
            node_filesystem_readonly{job="node_exporter"} == 0
          )
        for: 1h
        labels:
          severity: warning
        annotations:
          summary: "Filesystem is predicted to run out of space within the next 24 hours."
          description: 'Filesystem on {{ $labels.device }}, mounted on {{ $labels.mountpoint }}, at {{ $labels.instance }} has only {{ printf "%.2f" $value }}% available space left and is filling up.'

      - alert: NodeFilesystemSpaceFillingUp
        expr: |
          (
            node_filesystem_avail_bytes{job="node_exporter"} / node_filesystem_size_bytes{job="node_exporter"} * 100 < 20
          and
            predict_linear(node_filesystem_avail_bytes{job="node_exporter"}[6h], 4*60*60) < 0
          and
            node_filesystem_readonly{job="node_exporter"} == 0
          )
        for: 1h
        labels:
          severity: critical
        annotations:
          summary: "Filesystem is predicted to run out of space within the next 4 hours."
          description: 'Filesystem on {{ $labels.device }}, mounted on {{ $labels.mountpoint }}, at {{ $labels.instance }} has only {{ printf "%.2f" $value }}% available space left and is filling up fast.'

      - alert: NodeFilesystemAlmostOutOfSpace
        expr: |
          (
            node_filesystem_avail_bytes{job="node_exporter"} / node_filesystem_size_bytes{job="node_exporter"} * 100 < 5
          and
            node_filesystem_readonly{job="node_exporter"} == 0
          )
        for: 30m
        labels:
          severity: warning
        annotations:
          summary: "Filesystem has less than 5% space left."
          description: 'Filesystem on {{ $labels.device }}, mounted on {{ $labels.mountpoint }}, at {{ $labels.instance }} has only {{ printf "%.2f" $value }}% available space left.'

      - alert: NodeFilesystemAlmostOutOfSpace
        expr: |
          (
            node_filesystem_avail_bytes{job="node_exporter"} / node_filesystem_size_bytes{job="node_exporter"} * 100 < 3
          and
            node_filesystem_readonly{job="node_exporter"} == 0
          )
        for: 30m
        labels:
          severity: critical
        annotations:
          summary: "Filesystem has less than 3% space left."
          description: 'Filesystem on {{ $labels.device }}, mounted on {{ $labels.mountpoint }}, at {{ $labels.instance }} has only {{ printf "%.2f" $value }}% available space left.'
